services:
  - type: web
    name: ssp-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true

staticSites:
  - name: ssp-frontend
    repo: .
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    autoDeploy: true
